### PR TITLE
Corrected tab title on Q&A schedule page - Fixes #214

### LINKED ISSUE #214: bug: wrong tab title on Q&A schedule page
Upon going to the [Q&A schedule page](https://www.reactiflux.com/schedule) the title of the tab at the top shows *Transcripts* instead of something like *Schedule*

### PR DESCRIPTION
**Pull request by ANSH4195**
Corrected the tab title for Q&A Schedule pages from "Transcripts" to "Q&A Schedules".

### CODE REVIEW

File: src/pages/schedule.tsx [hunk 1]
```diff
@@ -31,7 +31,7 @@ export default function Schedule({
 }: Awaited<ReturnType<typeof getStaticProps>>["props"]) {
   return (
     <Layout
-      title="Transcripts"
+      title="Q&amp;A Schedules"
```
Comment (nickserv) [inline src/pages/schedule.tsx]: Let's use the same pluralization as the navbar link and page title:
```suggestion
      title="Q&amp;A Schedule"
```

**Review by nickserv — CHANGES_REQUESTED** [review]

**Review by vcarl — APPROVED** [review]
ty!

**Review by nickserv — APPROVED** [review]
